# creating student reports using list and dictonary

std1 = {"rollno": "BAIM-S20-001", "name": "Mohammed Usamah", "grades": "A"}
std2 = {"rollno": "BAIM-S20-002", "name": "Abdullah Maroof", "grades": "A+"}
std3 = {"rollno": "BAIM-S20-003", "name": "Mohammad Nisar", "grades": "A+"}
std4 = {"rollno": "BAIM-S20-004", "name": "Imran", "grades": "B"}
std5 = {"rollno": "BAIM-S20-005", "name": "Nabila Muaaz", "grades": "A+"}
std6 = {"rollno": "BAIM-S20-006", "name": "Farah Shahzad", "grades": "A"}
std7 = {"rollno": "BAIM-S20-007", "name": "Huzaifa Khan", "grades": "B"}

report = [std1,std2, std3, std4, std5, std6, std7]
print ("Full Report")
print(report)
print("-------------------------------------------------------------------")
print("Data of the First Student")
print("Name of First Student")
print(report[0]["name"])
print("Roll no of First Student")
print(report[0]["rollno"])
print("Grade of First Student")
print(report[0]["grades"])
print("-------------------------------------------------------------------")
print("Data of the Second Student")
print("Name of Second Student")
print(report[1]["name"])
print("Roll no of Second Student")
print(report[1]["rollno"])
print("Grade of Second Student")
print(report[1]["grades"])
print("-------------------------------------------------------------------")
print("Data of the Third Student")
print("Name of Third Student")
print(report[2]["name"])
print("Roll no of Third Student")
print(report[2]["rollno"])
print("Grade of Third Student")
print(report[2]["grades"])
print("-------------------------------------------------------------------")
print("Data of the Forth Student")
print("Name of Forth Student")
print(report[3]["name"])
print("Roll no of Forth Student")
print(report[3]["rollno"])
print("Grade of Forth Student")
print(report[3]["grades"])
print("-------------------------------------------------------------------")
print("Data of the Fifth Student")
print("Name of Fifth Student")
print(report[4]["name"])
print("Roll no of Fifth Student")
print(report[4]["rollno"])
print("Grade of Fifth Student")
print(report[4]["grades"])
print("-------------------------------------------------------------------")
print("Data of the Sixth Student")
print("Name of Sixth Student")
print(report[5]["name"])
print("Roll no of Sixth Student")
print(report[5]["rollno"])
print("Grade of Sixth Student")
print(report[5]["grades"])
print("-------------------------------------------------------------------")
print("Data of the Seventh Student")
print("Name of Seventh Student")
print(report[6]["name"])
print("Roll no of Seventh Student")
print(report[6]["rollno"])
print("Grade of Seventh Student")
print(report[6]["grades"])
print("-------------------------------------------------------------------")